CREATE TABLE `host_listings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`hostName` varchar(255) NOT NULL,
	`profilePhotoUrl` varchar(500),
	`languages` json NOT NULL,
	`bio` text NOT NULL,
	`email` varchar(320) NOT NULL,
	`wechatOrPhone` varchar(100) NOT NULL,
	`district` varchar(100) NOT NULL,
	`fullAddress` text,
	`availability` json NOT NULL,
	`maxGuests` int NOT NULL DEFAULT 2,
	`cuisineStyle` varchar(255) NOT NULL,
	`menuDescription` text NOT NULL,
	`foodPhotoUrls` json NOT NULL,
	`dietaryAccommodations` json,
	`mealDurationMinutes` int NOT NULL DEFAULT 120,
	`pricePerPerson` int NOT NULL DEFAULT 100,
	`kidsFriendly` boolean NOT NULL DEFAULT true,
	`hasPets` boolean NOT NULL DEFAULT false,
	`petDetails` varchar(255),
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `host_listings_id` PRIMARY KEY(`id`)
);
